services:
  app:
    build:
      context:
        .
    restart: unless-stopped
    environment:
      - DISCORD_API_TOKEN=${DISCORD_API_KEY}
      - CLIENT_ID
      - GUILD_ID
    volumes:
      - media:/app/sounds
      - database:/app/database

volumes:
  media:
  database:

